# Generated by Django 4.0.4 on 2022-04-18 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_basic', '0003_cart_cartitem_order_orderitem_delete_ordermodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='available_inventory',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
